log4j.rootLogger=WARN, file
log4j.logger.io.delta.sharing=DEBUG, file
log4j.logger.io.delta.standalone=DEBUG, file
log4j.logger.org.apache.hadoop.fs.s3a=WARN, file

log4j.appender.file=org.apache.log4j.FileAppender
log4j.appender.file.File=/var/log/delta-sharing/server.log
log4j.appender.file.Append=true
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] %m%n
