// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Containerized Lakehouse Platform Contributors

"use client";

import { useEffect, useState, useCallback } from "react";
import CodeExecGuard from "@/components/code-exec-guard";
import {
  Workflow,
  FileCode2,
  FileText,
  Plus,
  Loader2,
  AlertCircle,
  Terminal,
  Copy,
  Check,
  ChevronDown,
  ChevronRight,
  Layers,
  ArrowDown,
  Trash2,
  Download,
  Play,
  Search,
  History,
  Clock,
  CheckCircle2,
  XCircle,
  RotateCcw,
  Package,
  Database,
  Zap,
  ServerCog,
} from "lucide-react";

interface PipelineFile {
  path: string;
  content: string;
  modified: string;
}

interface PipelineData {
  specs: PipelineFile[];
  transformations: PipelineFile[];
}

interface TableDef {
  name: string;
  tier: "bronze" | "silver" | "gold";
  type: "materialized_view" | "streaming_table";
  source: string;
  description: string;
}

interface RunHistoryEntry {
  id: string;
  timestamp: string;
  spec: string;
  mode: "run" | "dry-run";
  exitCode: number | null;
  message: string | null;
  output: string;
  durationMs: number | null;
}

function formatDuration(ms: number | null): string {
  if (ms === null) return "—";
  if (ms < 1000) return `${ms}ms`;
  const s = Math.round(ms / 1000);
  if (s < 60) return `${s}s`;
  return `${Math.floor(s / 60)}m ${s % 60}s`;
}

function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffMin = Math.floor(diffMs / 60_000);
  if (diffMin < 1) return "just now";
  if (diffMin < 60) return `${diffMin}m ago`;
  const diffH = Math.floor(diffMin / 60);
  if (diffH < 24) return `${diffH}h ago`;
  return d.toLocaleDateString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }}
      className="rounded p-1 text-slate-500 hover:bg-slate-800 hover:text-slate-300"
      title="Copy to clipboard"
    >
      {copied ? (
        <Check size={14} className="text-emerald-400" />
      ) : (
        <Copy size={14} />
      )}
    </button>
  );
}

const tierColors = {
  bronze: { bg: "bg-amber-900/20", border: "border-amber-700/40", text: "text-amber-300", dot: "bg-amber-400" },
  silver: { bg: "bg-slate-700/20", border: "border-slate-500/40", text: "text-slate-300", dot: "bg-slate-400" },
  gold: { bg: "bg-yellow-900/20", border: "border-yellow-600/40", text: "text-yellow-300", dot: "bg-yellow-400" },
};

function generatePipelineCode(tables: TableDef[], pipelineName: string): { spec: string; code: string } {
  const safeName = pipelineName.toLowerCase().replace(/[^a-z0-9_]/g, "_");

  const spec = `name: ${safeName}
libraries:
  - glob:
      include: transformations/**
database: default
storage: s3a://lakehouse/warehouse
configuration:
  spark.sql.shuffle.partitions: "4"

  spark.hadoop.fs.s3a.endpoint: "http://seaweedfs:8333"
  spark.hadoop.fs.s3a.path.style.access: "true"
  spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
  spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
`;

  const imports = `"""
Spark Declarative Pipeline — ${pipelineName}

Generated by the Lakehouse Platform UI.
Run with: spark-pipelines run --spec ${safeName}.yml
"""

from pyspark import pipelines as dp
from pyspark.sql import functions as F
`;

  const tableDefs = tables.map((t) => {
    const decorator = t.type === "streaming_table" ? "@dp.streaming_table" : "@dp.materialized_view";
    let body: string;

    if (t.tier === "bronze" && !t.source) {
      body = `    # TODO: Replace with your data source
    # Example: spark.read.format("csv").load("s3a://lakehouse/raw/...")
    return spark.sql("SELECT 1 AS id, 'sample' AS value")`;
    } else if (t.source) {
      body = `    return (\n        spark.table("${t.source}")\n        # TODO: Add your transformations here\n    )`;
    } else {
      body = `    return spark.sql("SELECT 1 AS id")`;
    }

    return `
# ${t.description || `${t.tier.charAt(0).toUpperCase() + t.tier.slice(1)} layer: ${t.name}`}
${decorator}(name="${t.name}")
def ${t.name}():
${body}
`;
  });

  return { spec, code: imports + tableDefs.join("") };
}


function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

const PIPELINE_STEPS: { id: string; label: string; icon: typeof Trash2; onlyFullRefresh?: boolean; dryRunHide?: boolean }[] = [
  { id: "connect", label: "Connecting to Jupyter", icon: ServerCog },
  { id: "clean", label: "Cleaning S3 table data", icon: Trash2, onlyFullRefresh: true },
  { id: "deps", label: "Resolving dependencies", icon: Package },
  { id: "spark", label: "Starting Spark session", icon: Zap },
  { id: "pipeline", label: "Running pipeline transformations", icon: Workflow },
  { id: "sync", label: "Syncing tables to Unity Catalog", icon: Database, dryRunHide: true },
];

function PipelineProgress({
  elapsed,
  fullRefresh,
  mode,
  currentStep,
  logLines,
}: {
  elapsed: number;
  fullRefresh: boolean;
  mode: string;
  currentStep: string | null;
  logLines: string[];
}) {
  const steps = PIPELINE_STEPS.filter(s => {
    if (s.onlyFullRefresh && !fullRefresh) return false;
    if (s.dryRunHide && mode === "dry-run") return false;
    return true;
  });

  const activeIdx = currentStep ? steps.findIndex(s => s.id === currentStep) : 0;

  return (
    <div className="p-4 space-y-3">
      <div className="flex items-center gap-2 text-xs text-slate-500">
        <Clock size={12} />
        <span>Elapsed: <span className="text-slate-300 font-mono">{formatTime(elapsed)}</span></span>
      </div>
      <div className="space-y-0.5">
        {steps.map((step, i) => {
          const Icon = step.icon;
          const isActive = i === activeIdx;
          const isDone = i < activeIdx;
          return (
            <div
              key={step.id}
              className={`flex items-center gap-3 rounded-md px-3 py-2 text-xs transition-all duration-300 ${
                isActive
                  ? "bg-blue-950/30 border border-blue-800/30 text-blue-300"
                  : isDone
                    ? "text-emerald-400/70"
                    : "text-slate-600"
              }`}
            >
              {isDone ? (
                <CheckCircle2 size={14} className="text-emerald-500 shrink-0" />
              ) : isActive ? (
                <Loader2 size={14} className="animate-spin text-blue-400 shrink-0" />
              ) : (
                <Icon size={14} className="shrink-0" />
              )}
              <span className={isActive ? "font-medium" : ""}>{step.label}</span>
              {isActive && (
                <span className="ml-auto text-[10px] text-blue-400/60 font-mono">in progress</span>
              )}
              {isDone && (
                <span className="ml-auto text-[10px] text-emerald-500/50 font-mono">done</span>
              )}
            </div>
          );
        })}
      </div>
      {logLines.length > 0 && (
        <div className="mt-2 max-h-40 overflow-auto rounded border border-slate-800 bg-black/30 p-3">
          <pre className="font-mono text-[11px] leading-relaxed text-slate-400 whitespace-pre-wrap">
            {logLines.slice(-30).join("\n")}
          </pre>
        </div>
      )}
    </div>
  );
}

function PipelinesPageInner() {
  const [data, setData] = useState<PipelineData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"existing" | "builder" | "history">("existing");
  const [expandedFile, setExpandedFile] = useState<string | null>(null);

  // Builder state
  const [pipelineName, setPipelineName] = useState("my_pipeline");
  const [tables, setTables] = useState<TableDef[]>([
    { name: "bronze_raw", tier: "bronze", type: "materialized_view", source: "", description: "Raw data ingestion" },
    { name: "silver_cleaned", tier: "silver", type: "materialized_view", source: "bronze_raw", description: "Cleaned & validated data" },
    { name: "gold_aggregated", tier: "gold", type: "materialized_view", source: "silver_cleaned", description: "Business-level aggregation" },
  ]);
  const [generatedCode, setGeneratedCode] = useState<{ spec: string; code: string } | null>(null);
  const [saving, setSaving] = useState(false);
  const [saveResult, setSaveResult] = useState<string | null>(null);

  // Pipeline runner state
  const [running, setRunning] = useState(false);
  const [runStartTime, setRunStartTime] = useState<number | null>(null);
  const [runElapsed, setRunElapsed] = useState(0);
  const [currentStep, setCurrentStep] = useState<string | null>(null);
  const [streamLog, setStreamLog] = useState<string[]>([]);
  const [runOutput, setRunOutput] = useState<string | null>(null);
  const [runExitCode, setRunExitCode] = useState<number | null>(null);
  const [runMode, setRunMode] = useState<string | null>(null);
  const [runMessage, setRunMessage] = useState<string | null>(null);
  const [fullRefresh, setFullRefresh] = useState(true);

  // Run history (stored in the object store)
  const [history, setHistory] = useState<RunHistoryEntry[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [expandedRun, setExpandedRun] = useState<string | null>(null);

  const fetchHistory = useCallback(async () => {
    setHistoryLoading(true);
    try {
      const res = await fetch("/api/pipelines/history");
      if (res.ok) {
        const data = await res.json();
        setHistory(data.history || []);
      }
    } catch {
      // Silently fail — history is non-critical
    } finally {
      setHistoryLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchHistory();
  }, [fetchHistory]);

  const fetchPipelines = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/pipelines");
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      setData(await res.json());
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load pipelines");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchPipelines();
  }, [fetchPipelines]);

  useEffect(() => {
    if (!running) return;
    const interval = setInterval(() => {
      setRunElapsed(runStartTime ? Math.floor((Date.now() - runStartTime) / 1000) : 0);
    }, 1000);
    return () => clearInterval(interval);
  }, [running, runStartTime]);

  function addTable() {
    const tiers: Array<"bronze" | "silver" | "gold"> = ["bronze", "silver", "gold"];
    const lastTier = tables.length > 0 ? tables[tables.length - 1].tier : "bronze";
    const nextTier = tiers[Math.min(tiers.indexOf(lastTier) + 1, 2)];
    const lastName = tables.length > 0 ? tables[tables.length - 1].name : "";

    setTables([
      ...tables,
      {
        name: `${nextTier}_new_table`,
        tier: nextTier,
        type: "materialized_view",
        source: lastName,
        description: "",
      },
    ]);
  }

  function removeTable(idx: number) {
    setTables(tables.filter((_, i) => i !== idx));
  }

  function updateTable(idx: number, field: keyof TableDef, value: string) {
    setTables(
      tables.map((t, i) =>
        i === idx ? { ...t, [field]: value } : t
      )
    );
  }

  function handleGenerate() {
    setGeneratedCode(generatePipelineCode(tables, pipelineName));
  }

  async function handleSave() {
    if (!generatedCode) return;
    setSaving(true);
    setSaveResult(null);
    try {
      const safeName = pipelineName.toLowerCase().replace(/[^a-z0-9_]/g, "_");
      const res = await fetch("/api/pipelines", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          specName: `${safeName}.yml`,
          specContent: generatedCode.spec,
          transformations: [
            { path: `transformations/${safeName}.py`, content: generatedCode.code },
          ],
        }),
      });
      if (!res.ok) throw new Error(`${res.status}`);
      setSaveResult("Pipeline saved successfully!");
      await fetchPipelines();
    } catch (err) {
      setSaveResult(`Error: ${err instanceof Error ? err.message : "Failed to save"}`);
    } finally {
      setSaving(false);
    }
  }

  async function runPipeline(specPath: string, dryRun: boolean) {
    setRunning(true);
    setRunStartTime(Date.now());
    setRunElapsed(0);
    setCurrentStep(null);
    setStreamLog([]);
    setRunOutput(null);
    setRunExitCode(null);
    setRunMessage(null);
    setRunMode(dryRun ? "dry-run" : "run");
    try {
      const res = await fetch("/api/pipelines/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ specPath, dryRun, fullRefresh: !dryRun && fullRefresh }),
      });

      if (res.status === 409) {
        const data = await res.json();
        setRunOutput(data.error || "A pipeline is already running.");
        setRunExitCode(1);
        setRunMessage(data.error || "A pipeline is already running.");
        return;
      }

      if (!res.body) {
        setRunOutput("No response from server");
        setRunExitCode(1);
        return;
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let partial = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        partial += decoder.decode(value, { stream: true });
        const events = partial.split("\n\n");
        partial = events.pop() || "";

        for (const raw of events) {
          if (!raw.trim()) continue;
          const eventMatch = raw.match(/^event: (\w+)\ndata: ([\s\S]+)$/);
          if (!eventMatch) continue;
          const [, eventType, dataStr] = eventMatch;
          let payload: Record<string, unknown>;
          try { payload = JSON.parse(dataStr); } catch { continue; }

          switch (eventType) {
            case "step":
              setCurrentStep(payload.step as string);
              if (payload.label) {
                setStreamLog(prev => [...prev, payload.label as string]);
              }
              break;
            case "output":
              setStreamLog(prev => [...prev, payload.text as string]);
              break;
            case "error":
              setRunOutput(payload.message as string);
              setRunExitCode(1);
              setRunMessage(payload.message as string);
              break;
            case "done":
              setRunExitCode(payload.exitCode as number);
              setRunMessage(payload.message as string);
              setRunOutput(payload.output as string);
              break;
          }
        }
      }

      await fetchHistory();
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Failed to run pipeline";
      setRunOutput(msg);
      setRunExitCode(1);
    } finally {
      setRunning(false);
    }
  }

  async function clearHistory() {
    try {
      await fetch("/api/pipelines/history", { method: "DELETE", body: "{}" });
      setHistory([]);
      setExpandedRun(null);
    } catch {}
  }

  async function removeHistoryEntry(id: string) {
    try {
      const res = await fetch("/api/pipelines/history", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      if (res.ok) {
        const data = await res.json();
        setHistory(data.history || []);
      }
      if (expandedRun === id) setExpandedRun(null);
    } catch {}
  }

  return (
    <div className="mx-auto max-w-6xl space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Pipelines</h1>
        <p className="mt-1 text-sm text-slate-400">
          Spark Declarative Pipelines — medallion architecture
        </p>
      </div>

      {/* Architecture overview */}
      <div className="card flex items-center justify-between gap-6 overflow-x-auto">
        <div className="flex items-center gap-3">
          <div className={`rounded-lg border px-4 py-2 ${tierColors.bronze.bg} ${tierColors.bronze.border}`}>
            <p className={`text-xs font-bold ${tierColors.bronze.text}`}>Bronze</p>
            <p className="text-[10px] text-slate-400">Raw ingestion</p>
          </div>
          <ArrowDown size={16} className="rotate-[-90deg] text-slate-600" />
          <div className={`rounded-lg border px-4 py-2 ${tierColors.silver.bg} ${tierColors.silver.border}`}>
            <p className={`text-xs font-bold ${tierColors.silver.text}`}>Silver</p>
            <p className="text-[10px] text-slate-400">Cleaned & enriched</p>
          </div>
          <ArrowDown size={16} className="rotate-[-90deg] text-slate-600" />
          <div className={`rounded-lg border px-4 py-2 ${tierColors.gold.bg} ${tierColors.gold.border}`}>
            <p className={`text-xs font-bold ${tierColors.gold.text}`}>Gold</p>
            <p className="text-[10px] text-slate-400">Business aggregations</p>
          </div>
        </div>
        <div className="text-right">
          <p className="text-xs text-slate-400">Powered by</p>
          <p className="text-sm font-medium text-white">Spark Declarative Pipelines</p>
          <p className="font-mono text-[10px] text-slate-500">pyspark[pipelines] 4.1.1</p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 rounded-lg border border-slate-800 bg-surface p-1">
        {[
          { id: "existing" as const, label: "Existing Pipelines", icon: Layers },
          { id: "builder" as const, label: "Pipeline Builder", icon: Plus },
          { id: "history" as const, label: `Run History${running ? " (running)" : history.length > 0 ? ` (${history.length})` : ""}`, icon: History },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors ${
              activeTab === tab.id
                ? "bg-accent/10 text-accent"
                : "text-slate-400 hover:bg-slate-800 hover:text-white"
            }`}
          >
            <tab.icon size={16} />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Existing pipelines tab */}
      {activeTab === "existing" && (
        <div className="space-y-6">
          {error && (
            <div className="card flex items-center gap-3 border-red-900/50 bg-red-950/30 text-red-300">
              <AlertCircle size={18} />
              <span className="text-sm">{error}</span>
            </div>
          )}

          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 size={24} className="animate-spin text-slate-500" />
            </div>
          ) : data && (data.specs.length > 0 || data.transformations.length > 0) ? (
            <>
              {/* Pipeline specs */}
              {data.specs.length > 0 && (
                <div>
                  <h2 className="mb-3 flex items-center gap-2 text-sm font-semibold text-white">
                    <Workflow size={16} className="text-accent" />
                    Pipeline Specs
                  </h2>
                  <div className="space-y-2">
                    {data.specs.map((f) => (
                      <div key={f.path} className="rounded-lg border border-slate-800 bg-surface overflow-hidden">
                        <button
                          onClick={() => setExpandedFile(expandedFile === f.path ? null : f.path)}
                          className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-800/30"
                        >
                          <FileText size={16} className="text-amber-400" />
                          <div className="flex-1">
                            <p className="text-sm font-medium text-white">{f.path}</p>
                            <p className="text-[11px] text-slate-500">
                              Modified {new Date(f.modified).toLocaleDateString()}
                            </p>
                          </div>
                          {expandedFile === f.path ? (
                            <ChevronDown size={16} className="text-slate-500" />
                          ) : (
                            <ChevronRight size={16} className="text-slate-500" />
                          )}
                        </button>
                        {expandedFile === f.path && (
                          <div className="border-t border-slate-800 bg-surface-dark">
                            <div className="flex items-center justify-end px-4 py-1">
                              <CopyButton text={f.content} />
                            </div>
                            <pre className="overflow-x-auto px-4 pb-4 font-mono text-xs leading-relaxed text-emerald-300">
                              {f.content}
                            </pre>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Transformations */}
              {data.transformations.length > 0 && (
                <div>
                  <h2 className="mb-3 flex items-center gap-2 text-sm font-semibold text-white">
                    <FileCode2 size={16} className="text-purple-400" />
                    Transformations
                  </h2>
                  <div className="space-y-2">
                    {data.transformations.map((f) => {
                      const key = `t-${f.path}`;
                      return (
                        <div key={key} className="rounded-lg border border-slate-800 bg-surface overflow-hidden">
                          <button
                            onClick={() => setExpandedFile(expandedFile === key ? null : key)}
                            className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-800/30"
                          >
                            <FileCode2 size={16} className="text-purple-400" />
                            <div className="flex-1">
                              <p className="text-sm font-medium text-white">{f.path}</p>
                              <p className="text-[11px] text-slate-500">
                                Modified {new Date(f.modified).toLocaleDateString()}
                              </p>
                            </div>
                            {expandedFile === key ? (
                              <ChevronDown size={16} className="text-slate-500" />
                            ) : (
                              <ChevronRight size={16} className="text-slate-500" />
                            )}
                          </button>
                          {expandedFile === key && (
                            <div className="border-t border-slate-800 bg-surface-dark">
                              <div className="flex items-center justify-end px-4 py-1">
                                <CopyButton text={f.content} />
                              </div>
                              <pre className="overflow-x-auto px-4 pb-4 font-mono text-xs leading-relaxed text-blue-300">
                                {f.content}
                              </pre>
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="card text-center text-sm text-slate-500 py-12">
              No pipelines found. Use the Pipeline Builder to create one.
            </div>
          )}

          {/* Run pipelines */}
          <div className="card">
            <h2 className="mb-4 flex items-center gap-2 text-sm font-semibold text-white">
              <Terminal size={16} className="text-slate-400" />
              Run Pipelines
            </h2>

            <div className="mb-3 flex items-center gap-3">
              <label className="flex cursor-pointer items-center gap-2">
                <button
                  type="button"
                  role="switch"
                  aria-checked={fullRefresh}
                  onClick={() => setFullRefresh(!fullRefresh)}
                  className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition-colors ${
                    fullRefresh ? "bg-blue-600" : "bg-slate-700"
                  }`}
                >
                  <span
                    className={`inline-block h-3.5 w-3.5 rounded-full bg-white transition-transform ${
                      fullRefresh ? "translate-x-4" : "translate-x-0.5"
                    }`}
                  />
                </button>
                <span className="text-xs font-medium text-slate-300">Full Refresh</span>
              </label>
              <span className="text-xs text-slate-500">
                {fullRefresh
                  ? "Recompute all tables from scratch (--full-refresh-all)"
                  : "Incremental update (only process new/changed data)"}
              </span>
            </div>

            <div className="flex flex-wrap gap-3">
              {(data?.specs ?? []).map((spec) => {
                return (
                  <div key={spec.path} className="flex items-center gap-2">
                    <span className="text-xs text-slate-400 font-mono">{spec.path}</span>
                    <button
                      onClick={() => runPipeline(spec.path, false)}
                      disabled={running}
                      className="btn-primary flex items-center gap-1.5 text-xs"
                    >
                      {running && runMode === "run" ? (
                        <Loader2 size={14} className="animate-spin" />
                      ) : (
                        <Play size={14} />
                      )}
                      {fullRefresh ? "Full Refresh" : "Run"}
                    </button>
                    <button
                      onClick={() => runPipeline(spec.path, true)}
                      disabled={running}
                      className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-surface-dark px-3 py-2 text-xs font-medium text-slate-300 transition-colors hover:border-slate-600 hover:text-white"
                    >
                      {running && runMode === "dry-run" ? (
                        <Loader2 size={14} className="animate-spin" />
                      ) : (
                        <Search size={14} />
                      )}
                      Dry Run
                    </button>
                  </div>
                );
              })}
              {(!data || data.specs.length === 0) && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => runPipeline("spark-pipeline.yml", false)}
                    disabled={running}
                    className="btn-primary flex items-center gap-1.5 text-xs"
                  >
                    {running && runMode === "run" ? (
                      <Loader2 size={14} className="animate-spin" />
                    ) : (
                      <Play size={14} />
                    )}
                    {fullRefresh ? "Full Refresh" : "Run Pipeline"}
                  </button>
                  <button
                    onClick={() => runPipeline("spark-pipeline.yml", true)}
                    disabled={running}
                    className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-surface-dark px-3 py-2 text-xs font-medium text-slate-300 transition-colors hover:border-slate-600 hover:text-white"
                  >
                    {running && runMode === "dry-run" ? (
                      <Loader2 size={14} className="animate-spin" />
                    ) : (
                      <Search size={14} />
                    )}
                    Dry Run
                  </button>
                </div>
              )}
            </div>

            {/* Terminal output */}
            {(running || runOutput !== null) && (
              <div className="mt-4 rounded-lg border border-slate-800 bg-surface-dark overflow-hidden">
                <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
                  <span className="flex items-center gap-2 text-xs text-slate-400">
                    <Terminal size={14} />
                    {running ? (
                      <span className="flex items-center gap-2">
                        <Loader2 size={12} className="animate-spin" />
                        Running {runMode}...
                        <span className="font-mono text-slate-500">{formatTime(runElapsed)}</span>
                      </span>
                    ) : (
                      <span>
                        Pipeline {runMode} {runExitCode === 0 ? "completed" : "finished"}
                        {runExitCode !== null && (
                          <span className={runExitCode === 0 ? "text-emerald-400" : "text-red-400"}>
                            {" "}(exit {runExitCode})
                          </span>
                        )}
                      </span>
                    )}
                  </span>
                  {runOutput && <CopyButton text={runOutput} />}
                </div>
                {runMessage && !running && (
                  <div className={`mx-4 mt-3 rounded-lg px-3 py-2 text-xs font-medium ${
                    runExitCode === 0
                      ? "bg-emerald-950/40 text-emerald-300 border border-emerald-800/40"
                      : "bg-red-950/40 text-red-300 border border-red-800/40"
                  }`}>
                    {runMessage}
                  </div>
                )}
                {running ? (
                  <PipelineProgress
                    elapsed={runElapsed}
                    fullRefresh={fullRefresh}
                    mode={runMode || "run"}
                    currentStep={currentStep}
                    logLines={streamLog}
                  />
                ) : (
                  <pre className="max-h-96 overflow-auto p-4 font-mono text-xs leading-relaxed text-slate-300 whitespace-pre-wrap">
                    {runOutput}
                  </pre>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Run History tab */}
      {activeTab === "history" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="flex items-center gap-2 text-sm font-semibold text-white">
              <History size={16} className="text-slate-400" />
              Pipeline Run History
            </h2>
            {history.length > 0 && (
              <button
                onClick={clearHistory}
                className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-surface-dark px-3 py-1.5 text-xs font-medium text-slate-400 transition-colors hover:border-red-800 hover:text-red-400"
              >
                <Trash2 size={12} />
                Clear All
              </button>
            )}
          </div>

          {historyLoading && !running ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 size={24} className="animate-spin text-slate-500" />
            </div>
          ) : history.length === 0 && !running ? (
            <div className="card py-16 text-center">
              <Clock size={32} className="mx-auto mb-3 text-slate-600" />
              <p className="text-sm text-slate-400">No pipeline runs yet.</p>
              <p className="mt-1 text-xs text-slate-500">
                Run a pipeline from the Existing Pipelines tab to see results here.
              </p>
            </div>
          ) : (
            <div className="space-y-2">
              {running && (
                <div className="rounded-lg border border-blue-800/40 bg-blue-950/20 overflow-hidden">
                  <div className="flex w-full items-center gap-3 px-4 py-3">
                    <Loader2 size={18} className="shrink-0 animate-spin text-blue-400" />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-white">Pipeline running</span>
                        <span className={`rounded px-1.5 py-0.5 text-[10px] font-bold uppercase ${
                          runMode === "dry-run"
                            ? "bg-blue-900/30 text-blue-400 border border-blue-800/40"
                            : "bg-purple-900/30 text-purple-400 border border-purple-800/40"
                        }`}>
                          {runMode || "run"}
                        </span>
                      </div>
                      <div className="mt-0.5 flex items-center gap-3 text-[11px] text-slate-400">
                        <span className="flex items-center gap-1">
                          <Clock size={10} />
                          {formatTime(runElapsed)}
                        </span>
                        {currentStep && (
                          <span className="text-blue-400">
                            {PIPELINE_STEPS.find(s => s.id === currentStep)?.label || currentStep}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="border-t border-blue-900/30 px-4 py-3">
                    <PipelineProgress
                      elapsed={runElapsed}
                      fullRefresh={fullRefresh}
                      mode={runMode || "run"}
                      currentStep={currentStep}
                      logLines={streamLog}
                    />
                  </div>
                </div>
              )}
              {history.map((entry) => {
                const isExpanded = expandedRun === entry.id;
                const isSuccess = entry.exitCode === 0;
                const specName = entry.spec.split("/").pop() || entry.spec;

                return (
                  <div
                    key={entry.id}
                    className="rounded-lg border border-slate-800 bg-surface overflow-hidden"
                  >
                    <button
                      onClick={() => setExpandedRun(isExpanded ? null : entry.id)}
                      className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-800/30"
                    >
                      {isSuccess ? (
                        <CheckCircle2 size={18} className="shrink-0 text-emerald-400" />
                      ) : (
                        <XCircle size={18} className="shrink-0 text-red-400" />
                      )}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-medium text-white truncate">
                            {specName}
                          </span>
                          <span className={`rounded px-1.5 py-0.5 text-[10px] font-bold uppercase ${
                            entry.mode === "dry-run"
                              ? "bg-blue-900/30 text-blue-400 border border-blue-800/40"
                              : "bg-purple-900/30 text-purple-400 border border-purple-800/40"
                          }`}>
                            {entry.mode}
                          </span>
                          {entry.exitCode !== null && entry.exitCode !== 0 && (
                            <span className="rounded bg-red-950/40 px-1.5 py-0.5 text-[10px] font-mono text-red-400 border border-red-800/40">
                              exit {entry.exitCode}
                            </span>
                          )}
                        </div>
                        <div className="mt-0.5 flex items-center gap-3 text-[11px] text-slate-500">
                          <span className="flex items-center gap-1">
                            <Clock size={10} />
                            {formatTimestamp(entry.timestamp)}
                          </span>
                          <span>{formatDuration(entry.durationMs)}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            removeHistoryEntry(entry.id);
                          }}
                          className="rounded p-1 text-slate-600 hover:bg-slate-800 hover:text-red-400"
                          title="Remove from history"
                        >
                          <Trash2 size={12} />
                        </button>
                        {isExpanded ? (
                          <ChevronDown size={16} className="text-slate-500" />
                        ) : (
                          <ChevronRight size={16} className="text-slate-500" />
                        )}
                      </div>
                    </button>

                    {isExpanded && (
                      <div className="border-t border-slate-800 bg-surface-dark">
                        {entry.message && (
                          <div className={`mx-4 mt-3 rounded-lg px-3 py-2 text-xs font-medium ${
                            isSuccess
                              ? "bg-emerald-950/40 text-emerald-300 border border-emerald-800/40"
                              : "bg-red-950/40 text-red-300 border border-red-800/40"
                          }`}>
                            {entry.message}
                          </div>
                        )}
                        <div className="flex items-center justify-between border-b border-slate-800/50 px-4 py-2">
                          <span className="flex items-center gap-2 text-[11px] text-slate-500">
                            <Terminal size={12} />
                            <span className="font-mono">{entry.spec}</span>
                          </span>
                          <div className="flex items-center gap-1">
                            <CopyButton text={entry.output} />
                            <button
                              onClick={() => runPipeline(entry.spec, entry.mode === "dry-run")}
                              disabled={running}
                              className="flex items-center gap-1 rounded p-1 text-slate-500 hover:bg-slate-800 hover:text-accent"
                              title="Re-run this pipeline"
                            >
                              <RotateCcw size={12} />
                            </button>
                          </div>
                        </div>
                        <pre className="max-h-80 overflow-auto p-4 font-mono text-xs leading-relaxed text-slate-300 whitespace-pre-wrap">
                          {entry.output || "(no output)"}
                        </pre>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* Builder tab */}
      {activeTab === "builder" && (
        <div className="space-y-6">
          {/* Pipeline name */}
          <div className="card">
            <label className="mb-2 block text-sm font-semibold text-white">
              Pipeline Name
            </label>
            <input
              type="text"
              value={pipelineName}
              onChange={(e) => setPipelineName(e.target.value)}
              className="w-full rounded-lg border border-slate-700 bg-surface-dark px-3 py-2 font-mono text-sm text-white focus:border-accent focus:outline-none"
              placeholder="my_pipeline"
            />
          </div>

          {/* Table definitions */}
          <div className="card">
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-sm font-semibold text-white">
                Tables ({tables.length})
              </h2>
              <button onClick={addTable} className="btn-primary flex items-center gap-1.5 text-xs">
                <Plus size={14} />
                Add Table
              </button>
            </div>

            <div className="space-y-3">
              {tables.map((table, idx) => {
                const colors = tierColors[table.tier];
                return (
                  <div
                    key={idx}
                    className={`rounded-lg border p-4 ${colors.bg} ${colors.border}`}
                  >
                    <div className="mb-3 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <div className={`h-2 w-2 rounded-full ${colors.dot}`} />
                        <span className={`text-xs font-bold uppercase ${colors.text}`}>
                          {table.tier}
                        </span>
                      </div>
                      {tables.length > 1 && (
                        <button
                          onClick={() => removeTable(idx)}
                          className="rounded p-1 text-slate-500 hover:bg-slate-800 hover:text-red-400"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}
                    </div>

                    <div className="grid gap-3 sm:grid-cols-2">
                      <div>
                        <label className="mb-1 block text-[11px] text-slate-400">
                          Table name
                        </label>
                        <input
                          type="text"
                          value={table.name}
                          onChange={(e) => updateTable(idx, "name", e.target.value)}
                          className="w-full rounded border border-slate-700 bg-surface-dark px-2.5 py-1.5 font-mono text-xs text-white focus:border-accent focus:outline-none"
                        />
                      </div>
                      <div>
                        <label className="mb-1 block text-[11px] text-slate-400">
                          Tier
                        </label>
                        <select
                          value={table.tier}
                          onChange={(e) => updateTable(idx, "tier", e.target.value)}
                          className="w-full rounded border border-slate-700 bg-surface-dark px-2.5 py-1.5 text-xs text-white focus:border-accent focus:outline-none"
                        >
                          <option value="bronze">Bronze</option>
                          <option value="silver">Silver</option>
                          <option value="gold">Gold</option>
                        </select>
                      </div>
                      <div>
                        <label className="mb-1 block text-[11px] text-slate-400">
                          Type
                        </label>
                        <select
                          value={table.type}
                          onChange={(e) => updateTable(idx, "type", e.target.value)}
                          className="w-full rounded border border-slate-700 bg-surface-dark px-2.5 py-1.5 text-xs text-white focus:border-accent focus:outline-none"
                        >
                          <option value="materialized_view">Materialized View</option>
                          <option value="streaming_table">Streaming Table</option>
                        </select>
                      </div>
                      <div>
                        <label className="mb-1 block text-[11px] text-slate-400">
                          Source table (upstream)
                        </label>
                        <input
                          type="text"
                          value={table.source}
                          onChange={(e) => updateTable(idx, "source", e.target.value)}
                          className="w-full rounded border border-slate-700 bg-surface-dark px-2.5 py-1.5 font-mono text-xs text-white focus:border-accent focus:outline-none"
                          placeholder="e.g., bronze_raw"
                        />
                      </div>
                      <div className="sm:col-span-2">
                        <label className="mb-1 block text-[11px] text-slate-400">
                          Description
                        </label>
                        <input
                          type="text"
                          value={table.description}
                          onChange={(e) => updateTable(idx, "description", e.target.value)}
                          className="w-full rounded border border-slate-700 bg-surface-dark px-2.5 py-1.5 text-xs text-white focus:border-accent focus:outline-none"
                          placeholder="What does this table do?"
                        />
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Visual flow */}
            {tables.length > 1 && (
              <div className="mt-4 flex items-center gap-2 overflow-x-auto rounded-lg border border-slate-800 bg-surface-dark p-4">
                {tables.map((t, i) => {
                  const colors = tierColors[t.tier];
                  return (
                    <div key={i} className="flex items-center gap-2">
                      <div className={`whitespace-nowrap rounded border px-3 py-1.5 ${colors.bg} ${colors.border}`}>
                        <p className={`font-mono text-xs ${colors.text}`}>{t.name}</p>
                      </div>
                      {i < tables.length - 1 && (
                        <ArrowDown size={14} className="rotate-[-90deg] text-slate-600" />
                      )}
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Generate */}
          <div className="flex gap-3">
            <button onClick={handleGenerate} className="btn-primary flex items-center gap-2">
              <FileCode2 size={16} />
              Generate Code
            </button>
          </div>

          {/* Generated output */}
          {generatedCode && (
            <div className="space-y-4">
              <div className="rounded-lg border border-slate-800 bg-surface overflow-hidden">
                <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
                  <span className="flex items-center gap-2 text-xs font-medium text-slate-400">
                    <FileText size={14} />
                    {pipelineName.toLowerCase().replace(/[^a-z0-9_]/g, "_")}.yml
                  </span>
                  <CopyButton text={generatedCode.spec} />
                </div>
                <pre className="overflow-x-auto p-4 font-mono text-xs leading-relaxed text-emerald-300">
                  {generatedCode.spec}
                </pre>
              </div>

              <div className="rounded-lg border border-slate-800 bg-surface overflow-hidden">
                <div className="flex items-center justify-between border-b border-slate-800 px-4 py-2">
                  <span className="flex items-center gap-2 text-xs font-medium text-slate-400">
                    <FileCode2 size={14} />
                    transformations/{pipelineName.toLowerCase().replace(/[^a-z0-9_]/g, "_")}.py
                  </span>
                  <CopyButton text={generatedCode.code} />
                </div>
                <pre className="overflow-x-auto p-4 font-mono text-xs leading-relaxed text-blue-300">
                  {generatedCode.code}
                </pre>
              </div>

              {/* Save & run */}
              <div className="flex items-center gap-3">
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className="btn-primary flex items-center gap-2"
                >
                  {saving ? (
                    <Loader2 size={16} className="animate-spin" />
                  ) : (
                    <Download size={16} />
                  )}
                  Save to Pipelines Directory
                </button>
                {saveResult && (
                  <span
                    className={`text-xs ${
                      saveResult.startsWith("Error") ? "text-red-400" : "text-emerald-400"
                    }`}
                  >
                    {saveResult}
                  </span>
                )}
              </div>

              {saveResult && !saveResult.startsWith("Error") && (
                <div className="card border-emerald-900/30 bg-emerald-950/20">
                  <p className="mb-2 text-sm font-medium text-emerald-300">
                    Pipeline saved! Run it with:
                  </p>
                  <div className="flex items-center justify-between rounded-lg border border-slate-800 bg-surface-dark p-3">
                    <pre className="font-mono text-xs text-emerald-300">
                      spark-pipelines run
                    </pre>
                    <CopyButton
                      text="spark-pipelines run"
                    />
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function PipelinesPage() {
  return (
    <CodeExecGuard feature="Pipelines">
      <PipelinesPageInner />
    </CodeExecGuard>
  );
}
