#!/usr/bin/env bash
# pin-images.sh — supply-chain digest pinning for the container images the stack
# pulls (docs/testing.md — supply chain).
#
# A floating tag (postgres:16, apache/spark:4.1.0-...) can be re-pushed to point
# at different bytes. Pinning image@sha256:<digest> makes the pull reproducible
# and tamper-evident, the image analogue of jars.sha256. This script does not
# rewrite the compose/Dockerfiles for you; it maintains scripts/tools/images.lock
# (image -> digest) and checks that every image the stack references is covered.
#
# SSOT for which images we use = the `image:` lines in docker-compose-*.yml plus
# the `FROM` lines in every Dockerfile. Locally-built images (lakehouse-*,
# open-lakehouse-*) and multi-stage build aliases are skipped — only external,
# registry-pullable references are pinnable.
#
# Modes:
#   (default) --check   list referenced images and whether the lock covers them.
#                       Exit 0 (warn on gaps) unless --strict is given.
#   --lock              resolve each referenced image to a @sha256 digest via the
#                       first available of `docker manifest inspect`,
#                       `crane digest`, or `skopeo inspect`, and (re)write the
#                       lock. Run on a networked machine; commit the diff.
#   --strict            make an uncovered image a failure (for CI once populated).
#
# Portable to bash 3.2 (macOS): no associative arrays.
set -euo pipefail

MODE=check
STRICT=0
for a in "$@"; do
  case "$a" in
    --lock) MODE=lock ;;
    --check) MODE=check ;;
    --strict) STRICT=1 ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOCK="$ROOT/scripts/tools/images.lock"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

# --- Collect external image references from compose + Dockerfiles ------------
# compose:  `image: repo/name:tag`
# Dockerfile: `FROM repo/name:tag [AS stage]`  (strip the AS clause)
# Skip locally-built names and bare build-stage aliases (no registry/tag shape).
referenced_images() {
  {
    grep -rhE '^[[:space:]]*image:[[:space:]]*' "$ROOT"/docker-compose-*.yml 2>/dev/null \
      | sed -E 's/^[[:space:]]*image:[[:space:]]*//; s/[[:space:]]*$//'
    # FROM lines across every Dockerfile in the tree.
    find "$ROOT" -iname 'Dockerfile*' -not -path '*/node_modules/*' -print0 2>/dev/null \
      | xargs -0 grep -hE '^[[:space:]]*FROM[[:space:]]' 2>/dev/null \
      | sed -E 's/^[[:space:]]*FROM[[:space:]]+//; s/[[:space:]]+[Aa][Ss][[:space:]]+[A-Za-z0-9_.-]+[[:space:]]*$//; s/[[:space:]]*$//'
  } \
    | sed -E 's/^--platform=[^[:space:]]+[[:space:]]+//' \
    | grep -vE '^(lakehouse-|open-lakehouse-)' \
    | grep -E '[:@]' \
    | sort -u
}

lock_has() {  # $1 = image ref (repo:tag) — is there a digest entry for it?
  [ -f "$LOCK" ] || return 1
  awk -v n="$1" '$1==n{f=1} END{exit !f}' "$LOCK"
}

# Resolve repo:tag -> sha256:... using whatever registry tool is on PATH.
resolve_digest() {
  local ref="$1" d=""
  if command -v docker >/dev/null 2>&1; then
    # `docker manifest inspect -v` prints the descriptor digest; grab the first.
    d="$(docker manifest inspect "$ref" 2>/dev/null \
          | grep -oE 'sha256:[0-9a-f]{64}' | head -1 || true)"
  fi
  if [ -z "$d" ] && command -v crane >/dev/null 2>&1; then
    d="$(crane digest "$ref" 2>/dev/null || true)"
  fi
  if [ -z "$d" ] && command -v skopeo >/dev/null 2>&1; then
    d="$(skopeo inspect --format '{{.Digest}}' "docker://$ref" 2>/dev/null || true)"
  fi
  printf '%s' "$d"
}

IMAGES="$(referenced_images)"
[ -n "$IMAGES" ] || { echo "no external image references found" >&2; exit 1; }

if [ "$MODE" = lock ]; then
  echo "Resolving digests for referenced images → ${LOCK#"$ROOT"/}"
  tmp="$(mktemp)"
  {
    echo "# image digest lock for open-lakehouse (docs/testing.md — supply chain)."
    echo "# Format: <repo:tag> <sha256:...>   Generated by: scripts/tools/pin-images.sh --lock"
    echo "# Regenerate after any image bump and commit the diff. Pin compose/Dockerfiles"
    echo "# with repo@<digest> to actually enforce these at pull time."
  } > "$tmp"
  fail=0
  while IFS= read -r img; do
    [ -n "$img" ] || continue
    dig="$(resolve_digest "$img")"
    if [ -n "$dig" ]; then
      printf '%s %s\n' "$img" "$dig" >> "$tmp"
      printf '  %b✓%b %s %s\n' "$GREEN" "$NC" "$img" "$dig"
    else
      printf '  %b✗%b could not resolve digest for %s (no docker/crane/skopeo, or not pullable)\n' "$RED" "$NC" "$img" >&2
      fail=1
    fi
  done <<EOF
$IMAGES
EOF
  { grep '^#' "$tmp"; grep -v '^#' "$tmp" | sort; } > "$LOCK"
  rm -f "$tmp"
  echo "Lock written with $(grep -vc '^#' "$LOCK") entries."
  [ "$fail" -eq 0 ] || { echo "some images could not be resolved" >&2; exit 1; }
  exit 0
fi

# --- check mode --------------------------------------------------------------
echo "== container image digest-lock coverage =="
gaps=""
while IFS= read -r img; do
  [ -n "$img" ] || continue
  if lock_has "$img"; then
    printf '  %b✓%b %s (pinned)\n' "$GREEN" "$NC" "$img"
  else
    printf '  %b⚠%b %s (no digest in images.lock)\n' "$YELLOW" "$NC" "$img"
    gaps="$gaps $img"
  fi
done <<EOF
$IMAGES
EOF

if [ -n "$gaps" ]; then
  if [ "$STRICT" -eq 1 ]; then
    printf '%bimage digest lock incomplete%b — run: ./scripts/tools/pin-images.sh --lock\n' "$RED" "$NC" >&2
    exit 1
  fi
  printf '%b⚠ images.lock not yet populated%b — run on a networked machine:\n' "$YELLOW" "$NC"
  printf '   ./scripts/tools/pin-images.sh --lock   (then commit images.lock)\n'
  exit 0
fi
printf '%ball referenced images are digest-pinned.%b\n' "$GREEN" "$NC"
